package com;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;


import com.Store;
import com.StoreRepository;

@SpringBootApplication
@RestController
public class Application {

    @Autowired // This means to get the bean called storeRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StoreRepository storeRepository;

    @RequestMapping("/")
    public String greeting() {
        return "Hello World!";
    }

    @RequestMapping("/all")
	public @ResponseBody Iterable<Store> getAllStores() {
		return storeRepository.findAll();
    }
    
    @RequestMapping("/all2")
	public Iterable<Store> getAllStores2() {
		return storeRepository.findAll();
	}

    @RequestMapping("/1")
    public String route1() {
        return "1111xxxxx11111!";
    }

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}